name: deployProduction
on:
  push:
    branches: [master]
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn add node-jq
      - run: echo $(./node_modules/node-jq/bin/jq '.homepage = "https://clumsycomputer.github.io/gh-repos/"' package.json) > package.json
      - run: yarn build
        env:
          REACT_APP_BASEPATH: 'gh-repos'
          REACT_APP_OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
          REACT_APP_OAUTH_PROXY_URL: 'https://gh-repos-prod.herokuapp.com'
      - run: yarn add -D gh-pages
      - run: yarn gh-pages -d build
